services:
  registry:
    image: registry:2
    container_name: local-registry
    ports:
      - "5000:5000"
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
      - ./data:/var/lib/registry
    restart: unless-stopped
